# Generated by Django 3.2 on 2021-04-22 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_date', models.DateTimeField(auto_now_add=True)),
                ('side_1', models.TextField(default='')),
                ('side_1_direction', models.CharField(max_length=5)),
                ('side_2', models.TextField(default='')),
                ('side_2_direction', models.CharField(max_length=5)),
                ('curator_note', models.CharField(default='', max_length=255, null=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(to='stacks.Card')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_date', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('number_correct', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lexeme_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.card')),
            ],
        ),
    ]
