# Generated by Django 3.2 on 2021-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstack',
            name='default_side_1_direction',
            field=models.CharField(default='ltr', max_length=5),
        ),
        migrations.AddField(
            model_name='cardstack',
            name='default_side_2_direction',
            field=models.CharField(default='ltr', max_length=5),
        ),
    ]
